name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23.3.0 # Use the version your project requires
      
      - name: Enable Corepack and Yarn Berry
        run: |
          corepack enable
          corepack prepare yarn@4.9.1 --activate

      - name: Verify Yarn version
        run: yarn -v

      - name: Install dependencies
        run: yarn install --no-immutable